# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, upload_to='post-header-images'),
        ),
    ]
