# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 07:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradYear', models.CharField(blank=True, max_length=4)),
                ('gradDegreeClass', models.CharField(blank=True, max_length=50)),
                ('course', models.CharField(blank=True, max_length=50)),
                ('resAddr', models.TextField(blank=True)),
                ('resState', models.CharField(blank=True, max_length=50)),
                ('permAddr', models.TextField(blank=True)),
                ('permState', models.CharField(blank=True, max_length=50)),
                ('phone1', models.CharField(blank=True, max_length=13)),
                ('phone2', models.CharField(blank=True, max_length=13)),
                ('picture', models.ImageField(blank=True, upload_to='user-images')),
                ('fbProfile', models.URLField(blank=True, default='http://facebook.com')),
                ('twProfile', models.URLField(blank=True, default='http://twitter.com')),
                ('lnkProfile', models.URLField(blank=True, default='http://linkedin.com')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='campus.School')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
