# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 20:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='gradDegreeClass',
            field=models.CharField(blank=True, choices=[('1', 'First Class'), ('2', 'Second Class Upper'), ('3', 'Second Class Lower'), ('4', 'Third Class'), ('5', 'Pass')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
