# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 07:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_school_abbr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('zones', '0001_initial'),
        ('accounts', '0004_userfollowing'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCreationTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField()),
                ('role', models.PositiveIntegerField(default=0)),
                ('valid', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoordinatorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True)),
                ('area_or_zonal', models.IntegerField(blank=True)),
                ('area', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='zones.Area')),
            ],
        ),
        migrations.CreateModel(
            name='ExcoProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True)),
                ('area_or_zonal', models.IntegerField(blank=True, default=0)),
                ('area', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='zones.Area')),
            ],
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='studentProfile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gradYear', models.CharField(blank=True, max_length=4)),
                ('gradDegreeClass', models.CharField(blank=True, choices=[('1', 'First Class'), ('2', 'Second Class Upper'), ('3', 'Second Class Lower'), ('4', 'Third Class'), ('5', 'Pass')], max_length=50)),
                ('course', models.CharField(blank=True, max_length=50)),
                ('resAddr', models.TextField(blank=True)),
                ('resState', models.CharField(blank=True, max_length=50)),
                ('permAddr', models.TextField(blank=True)),
                ('permState', models.CharField(blank=True, max_length=50)),
                ('phone1', models.CharField(blank=True, max_length=13)),
                ('phone2', models.CharField(blank=True, max_length=13)),
                ('picture', models.ImageField(blank=True, upload_to='user-images')),
                ('fbProfile', models.URLField(blank=True, default='http://facebook.com')),
                ('twProfile', models.URLField(blank=True, default='http://twitter.com')),
                ('lnkProfile', models.URLField(blank=True, default='http://linkedin.com')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='zones.Area')),
                ('school', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='campus.School')),
                ('zone', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='zones.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='school',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='timeestamp',
            new_name='timestamp',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.AddField(
            model_name='excoprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='excoprofile',
            name='zone',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='zones.Zone'),
        ),
        migrations.AddField(
            model_name='coordinatorprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coordinatorprofile',
            name='zone',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='zones.Zone'),
        ),
        migrations.AddField(
            model_name='accountcreationtokens',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
