# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20171004_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatorprofile',
            name='picture',
            field=models.ImageField(default='defaults/no-image.png', upload_to='coord-picture'),
        ),
        migrations.AddField(
            model_name='excoprofile',
            name='picture',
            field=models.ImageField(default='defaults/no-image.png', upload_to='exco-picture'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='picture',
            field=models.ImageField(blank=True, default='defaults/no-image.png', upload_to='user-images'),
        ),
    ]
