# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20171004_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatorprofile',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zones.Area'),
        ),
        migrations.AlterField(
            model_name='coordinatorprofile',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zones.Zone'),
        ),
        migrations.AlterField(
            model_name='excoprofile',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zones.Area'),
        ),
        migrations.AlterField(
            model_name='excoprofile',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zones.Zone'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zones.Area'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zones.Zone'),
        ),
    ]
