# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_auto_20170914_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
