# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='abbr',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
