# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_remove_comment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcomment',
            name='type',
            field=models.IntegerField(choices=[(1, 'comment'), (2, 'child_comment')], default=1),
        ),
    ]
