# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_childcomment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childcomment',
            old_name='type',
            new_name='parent_type',
        ),
    ]
