# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_auto_20170904_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcomment',
            name='parent',
            field=models.IntegerField(),
        ),
    ]
