# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_auto_20170914_0700'),
        ('programs', '0002_auto_20170912_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeRegisteredAccomodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.Accommodation')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Programme')),
            ],
        ),
    ]
