# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 21:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0003_auto_20170918_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user_1',
        ),
        migrations.AddField(
            model_name='conversation',
            name='starter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='started_conv', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
